server:
  port: 0   # HTTP API yok, sadece initializer olduğu için random port

spring:
  application:
    name: kafka-topic-infra
  main:
    web-application-type: none

  kafka:
    bootstrap-servers: localhost:9092   # docker-compose içindeki kafka service adı
    admin:
      fail-fast: true
      properties:
        request.timeout.ms: 5000
        retry.backoff.ms: 1000
        retries: 10

logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: INFO