server:
  port: 0

spring:
  application:
    name: kafka-topic-infra
  main:
    web-application-type: none

  kafka:
    bootstrap-servers: kafka:9092
    admin:
      fail-fast: true
      properties:
        request.timeout.ms: 5000
        retry.backoff.ms: 1000
        retries: 10

logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: INFO